import {
  AlertCircle,
  ArrowRight,
  Check,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronDown,
  Circle,
  Copy,
  CreditCard,
  File,
  FileText,
  HelpCircle,
  ImageIcon,
  Laptop,
  Loader2,
  type LucideCrop as LucideProps,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Printer,
  Settings,
  SunMedium,
  Trash,
  User,
  X,
  Eye,
  EyeOff,
  Mail,
  Lock,
  MapPin,
  Calendar,
  Clock,
  Users,
  Activity,
  BarChart3,
  Home,
  Menu,
  Search,
  Bell,
  LogOut,
  Edit,
  Save,
  Upload,
  Download,
  Filter,
  SortAsc,
  SortDesc,
  RefreshCw,
  ExternalLink,
  Info,
  CheckCircle,
  XCircle,
  AlertTriangle,
  Star,
  Heart,
  Share,
  MessageSquare,
  Phone,
  Globe,
  Camera,
  Video,
  Mic,
  Volume2,
  VolumeX,
  Play,
  Pause,
  SkipBack,
  SkipForward,
  Repeat,
  Shuffle,
  Bookmark,
  Tag,
  Flag,
  Shield,
  Key,
  Database,
  Server,
  Cloud,
  Wifi,
  WifiOff,
  Bluetooth,
  Battery,
  BatteryLow,
  Power,
  PowerOff,
  Zap,
  Flame,
  Droplets,
  Sun,
  CloudRain,
  CloudSnow,
  Wind,
  Thermometer,
  Compass,
  Navigation,
  Map,
  Route,
  Car,
  Truck,
  Plane,
  Train,
  Ship,
  Bike,
  Milk as Walk,
  Building,
  Building2,
  Store,
  Factory,
  Warehouse,
  School,
  Hospital,
  Church,
  TreePine,
  Flower,
  Leaf,
  Sprout,
  Bug,
  Fish,
  Bird,
  Cat,
  Dog,
  Rabbit,
  Turtle,
  type LucideIcon,
} from "lucide-react"

export type Icon = LucideIcon

export const Icons = {
  logo: Command,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  chevronDown: ChevronDown,
  trash: Trash,
  post: FileText,
  page: File,
  media: ImageIcon,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  check: Check,
  copy: Copy,
  circle: Circle,
  alertCircle: AlertCircle,
  eye: Eye,
  eyeOff: EyeOff,
  mail: Mail,
  lock: Lock,
  mapPin: MapPin,
  calendar: Calendar,
  clock: Clock,
  users: Users,
  activity: Activity,
  barChart: BarChart3,
  home: Home,
  menu: Menu,
  search: Search,
  bell: Bell,
  logOut: LogOut,
  edit: Edit,
  save: Save,
  upload: Upload,
  download: Download,
  filter: Filter,
  sortAsc: SortAsc,
  sortDesc: SortDesc,
  refresh: RefreshCw,
  externalLink: ExternalLink,
  info: Info,
  checkCircle: CheckCircle,
  xCircle: XCircle,
  star: Star,
  heart: Heart,
  share: Share,
  messageSquare: MessageSquare,
  phone: Phone,
  globe: Globe,
  camera: Camera,
  video: Video,
  mic: Mic,
  volume: Volume2,
  volumeOff: VolumeX,
  play: Play,
  pause: Pause,
  skipBack: SkipBack,
  skipForward: SkipForward,
  repeat: Repeat,
  shuffle: Shuffle,
  bookmark: Bookmark,
  tag: Tag,
  flag: Flag,
  shield: Shield,
  key: Key,
  database: Database,
  server: Server,
  cloud: Cloud,
  wifi: Wifi,
  wifiOff: WifiOff,
  bluetooth: Bluetooth,
  battery: Battery,
  batteryLow: BatteryLow,
  power: Power,
  powerOff: PowerOff,
  zap: Zap,
  flame: Flame,
  droplets: Droplets,
  sunIcon: Sun,
  cloudRain: CloudRain,
  cloudSnow: CloudSnow,
  wind: Wind,
  thermometer: Thermometer,
  compass: Compass,
  navigation: Navigation,
  map: Map,
  route: Route,
  car: Car,
  truck: Truck,
  plane: Plane,
  train: Train,
  ship: Ship,
  bike: Bike,
  walk: Walk,
  building: Building,
  building2: Building2,
  store: Store,
  factory: Factory,
  warehouse: Warehouse,
  school: School,
  hospital: Hospital,
  church: Church,
  treePine: TreePine,
  flower: Flower,
  leaf: Leaf,
  sprout: Sprout,
  bug: Bug,
  fish: Fish,
  bird: Bird,
  cat: Cat,
  dog: Dog,
  rabbit: Rabbit,
  turtle: Turtle,
  printer: Printer,
}

// Missing Command import, using a placeholder
function Command(props: LucideProps) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m15 12-8.5 8.5c-.83.83-2.17.83-3 0 0 0 0 0 0 0a2.12 2.12 0 0 1 0-3L12 9" />
      <path d="M17.64 15 22 10.64" />
      <path d="m20.91 11.7-1.25-1.25c-.6-.6-.93-1.4-.93-2.25v-.86L16.01 4.6a5.56 5.56 0 0 0-3.94-1.64H8l.92.82A6.18 6.18 0 0 1 11 8.9v2.8a2 2 0 0 1-.59 1.42" />
    </svg>
  )
}
