-- Insert 5 real nest boxes into the database to replace mock data
INSERT INTO nest_boxes (
  id,
  name,
  description,
  qr_code,
  qr_code_id,
  box_type,
  latitude,
  longitude,
  status,
  installation_date,
  target_species,
  habitat_type,
  height_from_ground,
  facing_direction,
  entrance_hole_size,
  floor_dimensions,
  installer_name,
  sponsor_message,
  created_at,
  updated_at
) VALUES 
(
  gen_random_uuid(),
  'Central Park Bluebird Box',
  'Located near the Sheep Meadow in Central Park, perfect for Eastern Bluebirds',
  'NB001',
  'NB001',
  'standard',
  40.7794,
  -73.9632,
  'active',
  '2024-01-15',
  ARRAY['Eastern Bluebird'],
  'grassland',
  5,
  'east',
  1.5,
  '5x5 inches',
  'NYC Parks Volunteer Team',
  'Sponsored by the Central Park Conservancy',
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Prospect Park Robin Platform',
  'Platform nest box at the Long Meadow designed for American Robins',
  'NB002',
  'NB002',
  'platform',
  40.6602,
  -73.9690,
  'active',
  '2024-02-01',
  ARRAY['American Robin'],
  'deciduous_forest',
  4,
  'south',
  NULL,
  '8x8 inches',
  'Brooklyn Bird Club',
  'In memory of Sarah Johnson, bird lover',
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Battery Park Wren House',
  'Small entrance hole perfect for House Wrens near the waterfront',
  'NB003',
  'NB003',
  'standard',
  40.7033,
  -74.0170,
  'active',
  '2024-01-20',
  ARRAY['House Wren'],
  'urban',
  6,
  'west',
  1.25,
  '4x4 inches',
  'Manhattan Audubon Society',
  'Protecting urban wildlife',
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Brooklyn Bridge Park Swallow Box',
  'Specialized box for Tree Swallows with harbor views',
  'NB004',
  'NB004',
  'specialty',
  40.7024,
  -73.9969,
  'maintenance',
  '2023-12-10',
  ARRAY['Tree Swallow'],
  'wetland',
  8,
  'north',
  1.5,
  '5x5 inches',
  'Brooklyn Bridge Park Conservancy',
  'Supporting migratory birds',
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'High Line Chickadee Condo',
  'Multi-unit box for Black-capped Chickadees on the elevated park',
  'NB005',
  'NB005',
  'specialty',
  40.7480,
  -74.0048,
  'active',
  '2024-03-01',
  ARRAY['Black-capped Chickadee'],
  'urban',
  7,
  'east',
  1.125,
  '4x4 inches',
  'High Line Network',
  'Bringing nature to the city',
  NOW(),
  NOW()
);
