-- Creating 5 sample nest boxes for the map page
INSERT INTO public.nest_boxes (
  id,
  name,
  description,
  latitude,
  longitude,
  elevation,
  box_type,
  habitat_type,
  target_species,
  entrance_hole_size,
  height_from_ground,
  facing_direction,
  installation_date,
  status,
  qr_code_id,
  qr_code,
  installer_name,
  monitoring_frequency,
  accessibility_notes,
  created_at,
  updated_at
) VALUES 
(
  gen_random_uuid(),
  'Central Park Bluebird Box',
  'Located near the Great Lawn with excellent visibility for Eastern Bluebirds',
  40.7829,
  -73.9654,
  50,
  'standard',
  'grassland',
  ARRAY['Eastern Bluebird', 'Tree Swallow'],
  1.5,
  5,
  'east',
  '2024-03-15',
  'active',
  'CPB001',
  'https://nestbox.app/box/CPB001',
  'John Smith',
  'weekly',
  'Easy access from main path',
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Prospect Park Wren House',
  'Positioned in dense shrubland perfect for House Wrens',
  40.6602,
  -73.9690,
  75,
  'specialty',
  'deciduous_forest',
  ARRAY['House Wren', 'Carolina Wren'],
  1.25,
  4,
  'southeast',
  '2024-02-20',
  'active',
  'PPW002',
  'https://nestbox.app/box/PPW002',
  'Sarah Johnson',
  'bi-weekly',
  'Requires short hike through wooded area',
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Brooklyn Bridge Park Swallow Box',
  'Waterfront location ideal for Tree Swallows',
  40.7023,
  -73.9964,
  10,
  'platform',
  'wetland',
  ARRAY['Tree Swallow', 'Barn Swallow'],
  1.75,
  6,
  'south',
  '2024-01-10',
  'maintenance_needed',
  'BBP003',
  'https://nestbox.app/box/BBP003',
  'Mike Chen',
  'weekly',
  'Accessible via waterfront promenade',
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'High Line Chickadee Nest',
  'Urban elevated park setting for cavity nesters',
  40.7480,
  -74.0048,
  30,
  'standard',
  'urban',
  ARRAY['Black-capped Chickadee', 'White-breasted Nuthatch'],
  1.125,
  4,
  'west',
  '2024-04-01',
  'active',
  'HLC004',
  'https://nestbox.app/box/HLC004',
  'Emily Rodriguez',
  'monthly',
  'Located on elevated park structure',
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Staten Island Bluebird Trail Box #1',
  'First box in the Staten Island Bluebird Trail system',
  40.5795,
  -74.1502,
  100,
  'standard',
  'grassland',
  ARRAY['Eastern Bluebird', 'American Robin'],
  1.5,
  5,
  'northeast',
  '2024-02-28',
  'active',
  'SIB005',
  'https://nestbox.app/box/SIB005',
  'David Park',
  'weekly',
  'Open field location with vehicle access',
  NOW(),
  NOW()
);
